### PR TITLE
Exploring userprovided types for specific cols

### PR DESCRIPTION
**Pull request by codygman**
Mostly for review. It is very rough, but seems to be working. This should resolve what I wanted #66 to do.

### CODE REVIEW

**Comment by acowley** [comment]
Can you provide a test or at least an example usage to look at to make sure we're on the same page with expectations? Does the type override lookup have to be based on Strings? Why not use the usual template haskell `Name` quoting mechanism to pair a string column name with a bona fide type name that doesn't require the partial function to do the lookup?

**Comment by codygman** [comment]
Yes, I plan on doing all of those. I just wanted to throw this up in case I
got busy with something else ;)

**Comment by codygman** [comment]
I'm trying to add a test but wasn't sure how you wanted me to do it. I see `generateCode` is hardcoded to use tableTypes and then csvTests just calls it directly. I see a few different options:

- Check for special cases such as mine that uses overrides in csvTests
- Allow specifying arguments passed to tableTypes in examples.toml. Of course I guess you'd have to allow the entire tableTypes line and then eval it. I'm not sure this is a good option, though it is very declarative.

Hm, I guess those are my only ideas.

**Comment by acowley** [comment]
Yeah, it's not flexible enough as it stands. I had a situation where I would have preferred it call `tableType` instead of `tableTypes`. I was thinking of changing the protocol to look for specific keys other than `generated`. We could have keys `tableType` and `tableTypes`, and maybe do all of them or maybe just the first. I take it, though, that you want something more granular for passing options to `tableTypes`? I don't know how easy a generic `eval` would be, so I'd rather dispatch based on the key name if possible. 

What is the TH that you would like to verify in a test?

**Comment by codygman** [comment]
Reminder to self: the lenses created don't use the overrided type, need to fix.

**Comment by teto** [comment]
hi, would you mind rebasing this ? looks very interesting !

**Pull request closed without merging**
