### PR TITLE
flake: fixed overlay

### PR DESCRIPTION
**Pull request by teto**
Overlay is a top level flake attribute (without the system specialization).

### CODE REVIEW

**Comment by teto** [comment]
(otherwise, when referencing this flake from mine, nix complains the "Frames" overlay is invalid)/

**Comment by acowley** [comment]
Sorry I didn’t appreciate why you’d done it the way you did!

**Comment by teto** [comment]
thanks for merging it, it solved my issue. Flakes sole almost every face-visible UX issue I had with nix but it takes some time to master.  
I noticed that `nix develop` is broken for ghc8.10.7  (haskell-language-server issue). What do you think of having two development shells, one for ghc8107, one for 920 ? (hls does this for instance https://github.com/haskell/haskell-language-server/blob/3084651ba467c3306ffd7d1024fbd3a13a64a296/flake.nix#L340). 

HLS stopped caching their nix builds but according to a maintainer (also friend of mine), they should put it back soon so we should be able to add hls again in the devShell then.

**Comment by acowley** [comment]
Yeah, separating things sounds good. I’d actually like to have with and without hls shells as it’s too much of a production to get it working when you want to test new dependencies or small fixes.

**Comment by teto** [comment]
HLS provides shell with just ghc and cabal for this reason too so I can do sthg similar https://github.com/haskell/haskell-language-server/blob/3084651ba467c3306ffd7d1024fbd3a13a64a296/flake.nix#L331

**Pull request merged**
