### PR TITLE
[READY] Write csv separator

### PR DESCRIPTION
**Pull request by teto**
need to test it first :)

### CODE REVIEW

**Comment by acowley** [comment]
At first glance it looks right, but I’ll look closer later. Can we name the general one with a `DSV` suffix rather than `CSV`? I think it’s standard naming (Delimiter Separated Values), and there’s already the `Frames-dsv` package and the dsv package it depends on.

Part of me wishes we could rename `ParserOptions` now, but I think that would break user code without helping anyone.

**Comment by acowley** [comment]
Ah, except let’s not change the types on anything in the public API (`produceCSV`).

**Comment by teto** [comment]
fixed. seems to work for me

**Comment by acowley** [comment]
Perfect! Thank you!

**Pull request merged**
