### PR TITLE
TH fixes for ghc-8.8+ (TySynInstD and TySynEqn have different syntax)…

### PR DESCRIPTION
**Pull request by adamConnerSax**
- Fixed the TH.  Please double check!!
- Added ```TypeApplications``` to a few tests where necessary
- Wrapped the TH change and some imports of ```(<>)``` in CPP to make all compile, and without warnings, on ghc pre and post 8.8.

### CODE REVIEW

**Comment by acowley** [comment]
I think the TH fix is right.

There are a lot of white space adjustments here, too. If you're using a formatter, can you include a config file for it (if it takes one), and we should mention what formatter you're using.

**Comment by adamConnerSax** [comment]
Sorry about the whitespace.  On Monday I could do it again without the whitespace. I'm using Brittany from within emacs but without any config, just the defaults, I think.

**Comment by acowley** [comment]
I'd appreciate it if you could not include the formatting change in the one commit. I'm not dead set against using an auto formatter, but I'd at least like to separate it in the commit history.

I'm seeing more missing TypeApplications errors in other demo programs. Do you know what GHC change caused this?

**Comment by adamConnerSax** [comment]
Sure! Probably won’t get to it until Monday and it’ll be a new PR.

I don’t know about the TypeApplications. My guess—totally uninformed—is that some TH change led to generated code with a visible type application. But I don’t really know.

**Comment by acowley** [comment]
Okay, I've gotten everything running and I think I'm happy on both 8.6.5 and 8.8.2. How do you want to extract the formatting changes? Should I PR what I've done to your branch, or are you going to nuke that when you have time to reorganize the change? Or, if you'd prefer, I can wait for the new PR, and then deal with the merge on my end.

**Comment by acowley** [comment]
Alternatively, I'm not too fussed about leaving the formatting changes in as they are. I don't want to make more work for either of us.

**Comment by adamConnerSax** [comment]
What is easiest for you? I was only trying to help—and get a fork I could work from on 8.8.2. Anything you want to do now is fine by me.

**Comment by acowley** [comment]
Let's keep moving forward. The fixes are greatly appreciated!

**Comment by adamConnerSax** [comment]
Great!

**Pull request merged**
