### PR TITLE
add support for parsing ZonedTime from text

### PR DESCRIPTION
**Pull request by codygman**
I'm tried to start implementing what I was talking about in #56, but I'm stuck:

```
src/Main.hs:1:1: Exception when trying to run compile-time code: …
      Type ZonedTime isn't in scope
    Code: tableTypes "User" "user.csv"
Compilation failed.
```

Also, ColumnUniverse.hs is quite intimidating though I *sort of* have an intuition for what's going on there. I don't totally understand everything, but once I saw the pattern for the other CommonColumns it was pretty easy to duplicate. I feel I've probably not added something that was needed.

### CODE REVIEW

**Comment by acowley** [comment]
Can you add your (or some other) test code and data to the PR so we can be sure we're testing the same thing?

**Comment by codygman** [comment]
Sure, I might be able to get to it later. If not, probably tomorrow.

**Comment by codygman** [comment]
@acowley I couldn't actually figure out how to add tests TBH. I instead developed this by having a sample project and seeing what the type tableTypes generated was.

Here is my sample project and data: https://github.com/codygman/frames-date-test

**Comment by codygman** [comment]
superceded by #59

**Pull request closed without merging**
