### PR TITLE
Write records to csv

### PR DESCRIPTION
**Pull request by codygman**
- [x] Figure out how to mimic bases' `show` and ignore the `Identity { getIdentity = ... }` portion
- [x] create showFieldsText function
- [x] Figure out how to get Col values out of record
- [x] Figure out how to create a `showColText` function
- [x] figure out how to regenerate or keep original column header name
- [x] create pipe to stream rows to csv
- [x] create helper function that takes a record Producer, applies showFieldsText, then writes to csv line by line
- [ ] See if I can use UnColumns on rows and make writeCSV only take one row producer

How should regenerating the column name be handled? I'd prefer that the column name transformation be isomorphic, but I think that would require holding onto the column names somehow.

For now this just doesn't write a header.

### CODE REVIEW

**Comment by codygman** [comment]
@acowley After some research I now understand that the column names for each value are just type level symbols. It is still unclear how I would be able to access one though. I'm continuing to try and better and understand Frames/Vinyl and their respective pieces though.

**Comment by codygman** [comment]
@acowley I mostly figured it out but don't know how to avoid duplicating the rowProducer argument.

**Comment by codygman** [comment]
I tried this but got a *huge* type error:

```haskell
writeCsv :: ( AsVinyl rs
            , ColumnHeaders rs
            , AsVinyl ts
            , AllHave '[TextShow] ts
            , RecAll Identity (UnColumn ts) TextShow
            ) =>
            FilePath
         -> P.Producer (Record rs) IO ()
         -> P.Producer (Record ts) IO ()
         -> IO ()
writeCsv fp rows = do
  withFile fp WriteMode $ \h -> do
    rows' <- P.toListM (rows P.>-> P.take 1)
    case rows' of
      [firstRow] -> do
        let colHeaders = T.intercalate "," $ T.pack <$> columnHeaders (asProxyTypeOf firstRow)
            colHeaders' = colHeaders <> "\n"
          in
          T.hPutStr h colHeaders'
  withFile fp AppendMode $ \h -> P.runEffect $ uncolRows P.>-> writeCsvRow h
    where uncolRows = rows :: ( AsVinyl ts
                              , RecAll Identity (UnColumn ts) TextShow
                              ) => P.Producer (Record ts) IO ()
-- type error
-- C:\Users\cody\Frames\src\Frames\CSV.hs:184:3: error: …
--     * Couldn't match expected type `P.Producer (Record ts) IO ()
--                                     -> IO ()'
--                   with actual type `IO ()'
--     * In a stmt of a 'do' block:
--         withFile fp WriteMode
--         $ \ h
--             -> do { rows' <- P.toListM (rows P.>-> P.take 1);
--                     case rows' of { [firstRow] -> ... } }
--       In the expression:
--         do { withFile fp WriteMode $ \ h -> do { ... };
--              withFile fp AppendMode
--              $ \ h -> P.runEffect $ uncolRows P.>-> writeCsvRow h }
--       In an equation for `writeCsv':
--           writeCsv fp rows
--             = do { withFile fp WriteMode $ \ h -> ...;
--                    withFile fp AppendMode
--                    $ \ h -> P.runEffect $ uncolRows P.>-> writeCsvRow h }
--             where
--                 uncolRows
--                   = rows ::
--                       (AsVinyl ts, RecAll Identity (UnColumn ts) TextShow) =>
--                       P.Producer (Record ts) IO ()
--     * Relevant bindings include
--         writeCsv :: FilePath
--                     -> P.Producer (Record rs) IO ()
--                     -> P.Producer (Record ts) IO ()
--                     -> IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:183:1)
-- C:\Users\cody\Frames\src\Frames\CSV.hs:193:23: error: …
--     * Could not deduce: rs ~ ts1
--       from the context: (AsVinyl rs,
--                          ColumnHeaders rs,
--                          AsVinyl ts,
--                          AllHave '[TextShow] ts,
--                          RecAll Identity (UnColumn ts) TextShow)
--         bound by the type signature for:
--                    writeCsv :: (AsVinyl rs, ColumnHeaders rs, AsVinyl ts,
--                                 AllHave '[TextShow] ts, RecAll Identity (UnColumn ts) TextShow) =>
--                                FilePath
--                                -> P.Producer (Record rs) IO ()
--                                -> P.Producer (Record ts) IO ()
--                                -> IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:(173,1)-(182,17)
--       or from: (AsVinyl ts1, RecAll Identity (UnColumn ts1) TextShow)
--         bound by an expression type signature:
--                    (AsVinyl ts1, RecAll Identity (UnColumn ts1) TextShow) =>
--                    P.Producer (Record ts1) IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:(193,23)-(195,63)
--       `rs' is a rigid type variable bound by
--         the type signature for:
--           writeCsv :: forall (rs :: [*]) (ts :: [*]).
--                       (AsVinyl rs, ColumnHeaders rs, AsVinyl ts, AllHave '[TextShow] ts,
--                        RecAll Identity (UnColumn ts) TextShow) =>
--                       FilePath
--                       -> P.Producer (Record rs) IO ()
--                       -> P.Producer (Record ts) IO ()
--                       -> IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:173:13
--       `ts1' is a rigid type variable bound by
--         an expression type signature:
--           forall (ts1 :: [*]).
--           (AsVinyl ts1, RecAll Identity (UnColumn ts1) TextShow) =>
--           P.Producer (Record ts1) IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:193:31
--       Expected type: P.Producer (Record ts1) IO ()
--         Actual type: P.Producer (Record rs) IO ()
--     * In the expression:
--           rows ::
--             (AsVinyl ts, RecAll Identity (UnColumn ts) TextShow) =>
--             P.Producer (Record ts) IO ()
--       In an equation for `uncolRows':
--           uncolRows
--             = rows ::
--                 (AsVinyl ts, RecAll Identity (UnColumn ts) TextShow) =>
--                 P.Producer (Record ts) IO ()
--       In an equation for `writeCsv':
--           writeCsv fp rows
--             = do { withFile fp WriteMode $ \ h -> ...;
--                    withFile fp AppendMode
--                    $ \ h -> P.runEffect $ uncolRows P.>-> writeCsvRow h }
--             where
--                 uncolRows
--                   = rows ::
--                       (AsVinyl ts, RecAll Identity (UnColumn ts) TextShow) =>
--                       P.Producer (Record ts) IO ()
--     * Relevant bindings include
--         rows :: P.Producer (Record rs) IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:183:13)
--         writeCsv :: FilePath
--                     -> P.Producer (Record rs) IO ()
--                     -> P.Producer (Record ts) IO ()
--                     -> IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:183:1)
-- Compilation failed.
```

**Comment by codygman** [comment]
I'm starting to think I need to use the reifyConstraint function similiar to what is done in showFields.

**Comment by codygman** [comment]
Another quick attempt with more specific types and quantifiers. I still think the right approach will be using [reifyConstraint](https://github.com/acowley/Frames/blob/c8d5277a95608a44380757113637fb96a76126f2/src/Frames/Rec.hs#L52), here is the attempt anyway:

```haskell
f :: ( AsVinyl rs
     , ColumnHeaders rs
     , AsVinyl ts
     , RecAll Identity (UnColumn ts) TextShow
     ) =>
     P.Producer (Record rs) IO ()
  -> P.Producer (Record ts) IO ()
f = id
-- error
-- C:\Users\cody\Frames\src\Frames\CSV.hs:179:5: error: …
--     * Could not deduce: rs ~ ts
--       from the context: (AsVinyl rs,
--                          ColumnHeaders rs,
--                          AsVinyl ts,
--                          RecAll Identity (UnColumn ts) TextShow)
--         bound by the type signature for:
--                    f :: (AsVinyl rs, ColumnHeaders rs, AsVinyl ts,
--                          RecAll Identity (UnColumn ts) TextShow) =>
--                         P.Producer (Record rs) IO () -> P.Producer (Record ts) IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:(172,1)-(178,33)
--       `rs' is a rigid type variable bound by
--         the type signature for:
--           f :: forall (rs :: [*]) (ts :: [*]).
--                (AsVinyl rs, ColumnHeaders rs, AsVinyl ts,
--                 RecAll Identity (UnColumn ts) TextShow) =>
--                P.Producer (Record rs) IO () -> P.Producer (Record ts) IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:172:6
--       `ts' is a rigid type variable bound by
--         the type signature for:
--           f :: forall (rs :: [*]) (ts :: [*]).
--                (AsVinyl rs, ColumnHeaders rs, AsVinyl ts,
--                 RecAll Identity (UnColumn ts) TextShow) =>
--                P.Producer (Record rs) IO () -> P.Producer (Record ts) IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:172:6
--       Expected type: P.Producer (Record rs) IO ()
--                      -> P.Producer (Record ts) IO ()
--         Actual type: P.Producer (Record ts) IO ()
--                      -> P.Producer (Record ts) IO ()
--     * In the expression: id
--       In an equation for `f': f = id
--     * Relevant bindings include
--         f :: P.Producer (Record rs) IO () -> P.Producer (Record ts) IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:179:1)
-- Compilation failed.
```

**Comment by codygman** [comment]
A little different approach that also uses explicit foralls. I feel like this should have worked, then again it is late:

```haskell
writeCsv :: forall rs ts.
            ( AsVinyl rs
            , ColumnHeaders rs
            , AsVinyl ts
            , RecAll Identity (UnColumn ts) TextShow
            ) =>
            FilePath
         -> P.Producer (Record rs) IO ()
         -> IO ()
writeCsv fp rows = do
  withFile fp WriteMode $ \h -> do
    rows' <- P.toListM (rows P.>-> P.take 1)
    case rows' of
      [firstRow] -> do
        let colHeaders = T.intercalate "," $ T.pack <$> columnHeaders (asProxyTypeOf firstRow)
            colHeaders' = colHeaders <> "\n"
          in
          T.hPutStr h colHeaders'
  withFile fp AppendMode $ \h -> P.runEffect $ uncolRows rows P.>-> writeCsvRow h
    where uncolRows :: P.Producer (Rec Identity rs) IO () -> P.Producer (Record ts) IO ()
          uncolRows r = r P.>-> P.map toVinyl
-- type error:
-- C:\Users\cody\Frames\src\Frames\CSV.hs:238:39: error: …
--     * Could not deduce: UnColumn rs ~ ts
--       from the context: (AsVinyl rs,
--                          ColumnHeaders rs,
--                          AsVinyl ts,
--                          RecAll Identity (UnColumn ts) TextShow)
--         bound by the type signature for:
--                    writeCsv :: (AsVinyl rs, ColumnHeaders rs, AsVinyl ts,
--                                 RecAll Identity (UnColumn ts) TextShow) =>
--                                FilePath -> P.Producer (Record rs) IO () -> IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:(218,1)-(226,17)
--       `ts' is a rigid type variable bound by
--         the type signature for:
--           writeCsv :: forall (rs :: [*]) (ts :: [*]).
--                       (AsVinyl rs, ColumnHeaders rs, AsVinyl ts,
--                        RecAll Identity (UnColumn ts) TextShow) =>
--                       FilePath -> P.Producer (Record rs) IO () -> IO ()
--         at C:\Users\cody\Frames\src\Frames\CSV.hs:218:23
--       Expected type: Rec Identity rs -> Record ts
--         Actual type: Rec Identity rs -> Rec Identity (UnColumn rs)
--     * In the first argument of `P.map', namely `toVinyl'
--       In the second argument of `(P.>->)', namely `P.map toVinyl'
--       In the expression: r P.>-> P.map toVinyl
--     * Relevant bindings include
--         r :: P.Producer (Rec Identity rs) IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:238:21)
--         uncolRows :: P.Producer (Rec Identity rs) IO ()
--                      -> P.Producer (Record ts) IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:238:11)
--         rows :: P.Producer (Record rs) IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:227:13)
--         writeCsv :: FilePath -> P.Producer (Record rs) IO () -> IO ()
--           (bound at C:\Users\cody\Frames\src\Frames\CSV.hs:227:1)
-- Compilation failed.
```

**Comment by acowley** [comment]
Take a look at what I added in cd6367c4ed413c265eff51de57dbefa19c0cbc2e to see if it does what you need. It's not yet as flexible as it probably should be.

**Comment by codygman** [comment]
Yep, that looks like what I need. I need a text version though, so I'll
submit a PR with that and copy your test for it.

I was trying to figure out how to write the test for this function too, so
nice to see that and figure out where I was wrong. Same for the producer.

Thanks!

**Comment by acowley** [comment]
I started out doing it as `Text` but switched strategies at some point. The `showFields` thing gives `String`s and the `pipes` `Consumer` I found wanted `String` so I went with the flow. We should have a `showFields` for `Text` as well as `String`.

Not sure what the smoothest way to add that would be.

**Comment by codygman** [comment]
@acowley Understandable. I actually created a `showFieldsText` in https://github.com/codygman/Frames/commit/8f1dcb2bed15bafd41beaf6f9d374653adcf8762

**Pull request closed without merging**
