### PR TITLE
ghc9.2 support

### PR DESCRIPTION
**Pull request by teto**
This is a dirty mashup of different things to test ghc9.2 support.
I reference some unmerged patches etc so it's not ready yet for
merging but within a nix-shell (or `nix develop`), Frames compiles.

### CODE REVIEW

**Comment by acowley** [comment]
If the only concern is pulling in unreleased patches in `flake.nix`, I'd go ahead and merge this. We can back those changes out as doing so becomes possible. What do you think?

**Comment by acowley** [comment]
I needed this change to get the tests running (along with the necessary dependency in `Frames.cabal`).

```
diff --git a/test/DataCSV.hs b/test/DataCSV.hs
index 86a2231..c8b7fab 100644
--- a/test/DataCSV.hs
+++ b/test/DataCSV.hs
@@ -2,10 +2,12 @@
 module DataCSV where
 import Control.Monad ((>=>))
 import Data.Bifunctor (first)
+import qualified Data.ByteString as BS
 import qualified Data.HashMap.Lazy as H
 import Data.Maybe (catMaybes)
 import qualified Data.Text as T
 import qualified Data.Text.IO as T
+import Data.Text.Encoding (decodeUtf8)
 import Language.Haskell.TH.Syntax (Lift(..))
 import Text.Toml
 import Text.Toml.Types (Node (VTable, VString), Table)
@@ -20,8 +22,11 @@ data CsvExample = CsvExample {
 --   lift (CsvExample n c g) = [e| CsvExample n c g |]
 
 examplesFrom :: FilePath -> IO [CsvExample]
-examplesFrom fp = (either error id . ((first show . parseTomlDoc "examples") >=> go))
-                <$> T.readFile fp
+examplesFrom fp =
+  (either error id
+   . ((first show . parseTomlDoc "examples") >=> go)
+   . decodeUtf8)
+  <$> BS.readFile fp
   where go :: Table -> Either String [CsvExample]
         go = fmap catMaybes . mapM (uncurry ex . first T.unpack) . H.toList
         ex :: String -> Node -> Either String (Maybe CsvExample)
```

Let's also switch `flake.nix` to use `flake-utils.lib.eachDefaultSystem`. With these changes, the test suites are passing on 9.2.1 on aarch64-darwin for me.

**Comment by teto** [comment]
feel free to push to this branch or open a new one, seems like you have everything solved on your end ;)

**Comment by acowley** [comment]
Thank you for getting this rolling! I pulled in all your commits, then layered my changes on top of them and did a bit more shuffling around in the `flake.nix`. That file is still kind of a tangle; it would be nice to figure out a better approach to relaxing upper bounds, disabling haddock, and disabling tests more broadly on the transitive dependencies but those all seem like temporary hacks, so keeping them visible has some advantage.

**Comment by acowley** [comment]
And an additional thanks for your work opening PRs to get things updated across the ecosystem! Every time I went to look what was going on with one of these issues, I saw that you'd already taken care of it.

**Pull request merged**
